[package]
name = "clippy-mangen"
version = "0.1.0"
authors = ["Justin Bacher <92jbach@gmail.com>"]

[dependencies]
clippy = { path = "../app" }
clap = "4.5"
clap_complete = "4.5"
clap_mangen = "0.2"
itertools = "0.13"
