name: Rust
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup component add clippy
          rustup toolchain install nightly --profile minimal
          rustup component add rustfmt --toolchain nightly

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rust
          shared-key: ubuntu-latest@debug

      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Format
        run: cargo +nightly fmt --all -- --check --verbose
      - name: Test
        run: cargo test --verbose
